services:
  postgres:
    image: postgres:15-alpine
    container_name: beer_bot_postgres
    environment:
      POSTGRES_DB: beer_bot
      POSTGRES_USER: bot_user
      POSTGRES_PASSWORD: bot_password
      TZ: Europe/Moscow  # Set PostgreSQL server timezone to UTC+3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bot_user -d beer_bot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bot_network
  bot:
    build: .
    container_name: beer_bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DATABASE_URL: postgresql+asyncpg://bot_user:bot_password@postgres:5432/beer_bot
      LOG_LEVEL: DEBUG
      LOG_FILE: ${LOG_FILE:-bot.log}
      TZ: Europe/Moscow  # Set bot container timezone to UTC+3
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/bash
    networks:
      - bot_network
    restart: unless-stopped
volumes:
  postgres_data:
networks:
  bot_network:
    driver: bridge